services:
  - type: web
    name: isabelly-api
    env: node
    plan: free
    repo: https://github.com/NagoToxic/isabelly-api
    branch: main
    buildCommand: ""       # Dockerfile cuida do build
    startCommand: ""       # Dockerfile jรก define CMD
    dockerfilePath: Dockerfile
    envVars:
      - key: PORT
        value: 3000
      - key: ADMIN_KEY
        value: "sua_admin_key_aqui"
      - key: API_KEYS
        value: "Nago,chave2"
    healthCheckPath: /api/health