services:
  - type: web
    name: isabelly-api
    env: node
    plan: free
    branch: main
    buildCommand: |
      apt-get update && apt-get install -y \
        chromium \
        fonts-freefont-ttf \
        libcairo2-dev \
        libpango1.0-dev \
        libjpeg-dev \
        libgif-dev \
        librsvg2-dev
      npm install
    startCommand: node src/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: true
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/chromium
